In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/train.csv')

In [ ]:
df.head()

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,0x1602,CUS_0xd40,January,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,_,809.98,26.822620,22 Years and 1 Months,No,49.574949,80.41529543900253,High_spent_Small_value_payments,312.49408867943663,Good
1,0x1603,CUS_0xd40,February,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,31.944960,NaN,No,49.574949,118.28022162236736,Low_spent_Large_value_payments,284.62916249607184,Good
2,0x1604,CUS_0xd40,March,Aaron Maashoh,-500,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,28.609352,22 Years and 3 Months,No,49.574949,81.699521264648,Low_spent_Medium_value_payments,331.2098628537912,Good
3,0x1605,CUS_0xd40,April,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,31.377862,22 Years and 4 Months,No,49.574949,199.4580743910713,Low_spent_Small_value_payments,223.45130972736786,Good
4,0x1606,CUS_0xd40,May,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,Good,809.98,24.797347,22 Years and 5 Months,No,49.574949,41.420153086217326,High_spent_Medium_value_payments,341.48923103222177,Good

In [ ]:
df.shape

(16861, 28)

In [ ]:
df.isnull().sum()

ID                             0
Customer_ID                    0
Month                          0
Name                        1668
Age                            0
SSN                            0
Occupation                     0
Annual_Income                  0
Monthly_Inhand_Salary       2531
Num_Bank_Accounts              0
Num_Credit_Card                0
Interest_Rate                  0
Num_of_Loan                    0
Type_of_Loan                1856
Delay_from_due_date            0
Num_of_Delayed_Payment      1191
Changed_Credit_Limit           0
Num_Credit_Inquiries         344
Credit_Mix                     0
Outstanding_Debt               0
Credit_Utilization_Ratio       0
Credit_History_Age          1550
Payment_of_Min_Amount          0
Total_EMI_per_month            0
Amount_invested_monthly      729
Payment_Behaviour              1
Monthly_Balance              215
Credit_Score                   1
dtype: int64

# filling numeric data using mean/median

In [ ]:
df.fillna(df.mean(numeric_only=True),inplace=True)

#filling catogoric data using mode

In [ ]:
df.fillna(df.mode().iloc[0],inplace=True)

In [ ]:
df.isnull().sum()

ID                          0
Customer_ID                 0
Month                       0
Name                        0
Age                         0
SSN                         0
Occupation                  0
Annual_Income               0
Monthly_Inhand_Salary       0
Num_Bank_Accounts           0
Num_Credit_Card             0
Interest_Rate               0
Num_of_Loan                 0
Type_of_Loan                0
Delay_from_due_date         0
Num_of_Delayed_Payment      0
Changed_Credit_Limit        0
Num_Credit_Inquiries        0
Credit_Mix                  0
Outstanding_Debt            0
Credit_Utilization_Ratio    0
Credit_History_Age          0
Payment_of_Min_Amount       0
Total_EMI_per_month         0
Amount_invested_monthly     0
Payment_Behaviour           0
Monthly_Balance             0
Credit_Score                0
dtype: int64

In [ ]:
df

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,0x1602,CUS_0xd40,January,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,_,809.98,26.822620,22 Years and 1 Months,No,49.574949,80.41529543900253,High_spent_Small_value_payments,312.49408867943663,Good
1,0x1603,CUS_0xd40,February,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,4302.357054,3,...,Good,809.98,31.944960,17 Years and 3 Months,No,49.574949,118.28022162236736,Low_spent_Large_value_payments,284.62916249607184,Good
2,0x1604,CUS_0xd40,March,Aaron Maashoh,-500,821-00-0265,Scientist,19114.12,4302.357054,3,...,Good,809.98,28.609352,22 Years and 3 Months,No,49.574949,81.699521264648,Low_spent_Medium_value_payments,331.2098628537912,Good
3,0x1605,CUS_0xd40,April,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,4302.357054,3,...,Good,809.98,31.377862,22 Years and 4 Months,No,49.574949,199.4580743910713,Low_spent_Small_value_payments,223.45130972736786,Good
4,0x1606,CUS_0xd40,May,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,Good,809.98,24.797347,22 Years and 5 Months,No,49.574949,41.420153086217326,High_spent_Medium_value_payments,341.48923103222177,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16856,0x78c6,CUS_0xac7b,January,Jessica Wohlt,45,651-72-0851,_______,27288.85,2524.070833,5,...,Standard,1354.13,24.491286,19 Years and 1 Months,Yes,65.728137,103.50839885340244,Low_spent_Medium_value_payments,363.170547798588,Standard
16857,0x78c7,CUS_0xac7b,February,Jessica Wohlt,45,651-72-0851,Developer,27288.85,4302.357054,5,...,Standard,1354.13,29.684491,19 Years and 2 Months,Yes,65.728137,82.90226263094056,Low_spent_Large_value_payments,373.7766840210498,Standard
16858,0x78c8,CUS_0xac7b,March,Jessica Wohlt,45,651-72-0851,Developer,27288.85,2524.070833,5,...,_,1354.13,26.256459,19 Years and 3 Months,NM,65.728137,64.31112657418517,!@9#%8,362.36782007780516,Standard
16859,0x78c9,CUS_0xac7b,April,Jessica Wohlt,45,651-72-0851,Developer,27288.85,4302.357054,5,...,Standard,1354.13,32.911280,19 Years and 4 Months,Yes,50918.000000,338.72689556032606,Low_spent_Small_value_payments,137.95205109166432,Standard
16860,0x78ca,CUS_0xac7b,May,Jessica Wohlt,45,651-72-0851,Developer,27288.85,2524.070833,5,...,Standard,1354.13,34.870039,19 Years and 5 Months,Yes,65.728137,338.5665,Low_spent_Small_value_payments,0.6882987789595063,Standard

# adding new columns

In [ ]:
# Convert required columns to numeric
numeric_cols = [
    "Annual_Income",
    "Outstanding_Debt",
    "Num_Bank_Accounts",
    "Num_Credit_Card",
    "Total_EMI_per_month",
    "Amount_invested_monthly",
    "Num_of_Delayed_Payment",
    "Num_of_Loan",
    "Num_Credit_Inquiries",
    "Credit_Utilization_Ratio",
    "Interest_Rate"
]

for col in numeric_cols:
    df[col] = pd.to_numeric(
        df[col].astype(str).str.replace("_", "", regex=False),
        errors="coerce"
    )


# 1. Monthly Income
df["Monthly_Income_Calc"] = df["Annual_Income"] / 12


# 2. Debt-to-Income Ratio
df["Debt_to_Income_Ratio"] = (
    df["Outstanding_Debt"] / (df["Annual_Income"] + 1)
)


# 3. Debt per Bank Account
df["Debt_per_Bank_Account"] = (
    df["Outstanding_Debt"] / (df["Num_Bank_Accounts"] + 1)
)


# 4. Debt per Credit Card
df["Debt_per_Credit_Card"] = (
    df["Outstanding_Debt"] / (df["Num_Credit_Card"] + 1)
)


# 5. Credit Card to Bank Account Ratio
df["Credit_to_Bank_Ratio"] = (
    df["Num_Credit_Card"] / (df["Num_Bank_Accounts"] + 1)
)


# 6. EMI to Income Ratio
df["EMI_to_Income_Ratio"] = (
    df["Total_EMI_per_month"] / (df["Monthly_Income_Calc"] + 1)
)


# 7. Investment to Income Ratio
df["Investment_to_Income_Ratio"] = (
    df["Amount_invested_monthly"] / (df["Monthly_Income_Calc"] + 1)
)


# 8. Delayed Payment Ratio
df["Delayed_Payment_Ratio"] = (
    df["Num_of_Delayed_Payment"] / (df["Num_of_Loan"] + 1)
)


# 9. Credit Inquiry per Credit Card
df["Inquiry_per_Credit_Card"] = (
    df["Num_Credit_Inquiries"] / (df["Num_Credit_Card"] + 1)
)


# 10. Total Financial Burden
df["Total_Financial_Burden"] = (
    df["Outstanding_Debt"]
    + df["Total_EMI_per_month"]
    + df["Amount_invested_monthly"]
)


# Check the new columns
new_cols = [
    "Monthly_Income_Calc",
    "Debt_to_Income_Ratio",
    "Debt_per_Bank_Account",
    "Debt_per_Credit_Card",
    "Credit_to_Bank_Ratio",
    "EMI_to_Income_Ratio",
    "Investment_to_Income_Ratio",
    "Delayed_Payment_Ratio",
    "Inquiry_per_Credit_Card",
    "Total_Financial_Burden"
]

print(df[new_cols].head())

   Monthly_Income_Calc  Debt_to_Income_Ratio  Debt_per_Bank_Account  \
0          1592.843333              0.042374                202.495
1          1592.843333              0.042374                202.495
2          1592.843333              0.042374                202.495
3          1592.843333              0.042374                202.495
4          1592.843333              0.042374                202.495

   Debt_per_Credit_Card  Credit_to_Bank_Ratio  EMI_to_Income_Ratio  \
0               161.996                   1.0             0.031104
1               161.996                   1.0             0.031104
2               161.996                   1.0             0.031104
3               161.996                   1.0             0.031104
4               161.996                   1.0             0.031104

   Investment_to_Income_Ratio  Delayed_Payment_Ratio  Inquiry_per_Credit_Card  \
0                    0.050454                    1.4                      0.8
1                    0.074211                    3.4                      0.8
2                    0.051259                    1.4                      0.8
3                    0.125143                    0.8                      0.8
4                    0.025988                    3.4                      0.8

   Total_Financial_Burden
0              939.970245
1              977.835171
2              941.254470
3             1059.013024
4              900.975102

In [ ]:
df.shape

(16861, 38)

In [ ]:
df

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Monthly_Income_Calc,Debt_to_Income_Ratio,Debt_per_Bank_Account,Debt_per_Credit_Card,Credit_to_Bank_Ratio,EMI_to_Income_Ratio,Investment_to_Income_Ratio,Delayed_Payment_Ratio,Inquiry_per_Credit_Card,Total_Financial_Burden
0,0x1602,CUS_0xd40,January,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,1592.843333,0.042374,202.495000,161.9960,1.0,0.031104,0.050454,1.4,0.8,939.970245
1,0x1603,CUS_0xd40,February,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,4302.357054,3,...,1592.843333,0.042374,202.495000,161.9960,1.0,0.031104,0.074211,3.4,0.8,977.835171
2,0x1604,CUS_0xd40,March,Aaron Maashoh,-500,821-00-0265,Scientist,19114.12,4302.357054,3,...,1592.843333,0.042374,202.495000,161.9960,1.0,0.031104,0.051259,1.4,0.8,941.254470
3,0x1605,CUS_0xd40,April,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,4302.357054,3,...,1592.843333,0.042374,202.495000,161.9960,1.0,0.031104,0.125143,0.8,0.8,1059.013024
4,0x1606,CUS_0xd40,May,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,1592.843333,0.042374,202.495000,161.9960,1.0,0.031104,0.025988,3.4,0.8,900.975102
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16856,0x78c6,CUS_0xac7b,January,Jessica Wohlt,45,651-72-0851,_______,27288.85,2524.070833,5,...,2274.070833,0.049620,225.688333,338.5325,0.5,0.028891,0.045497,1.6,1.0,1523.366536
16857,0x78c7,CUS_0xac7b,February,Jessica Wohlt,45,651-72-0851,Developer,27288.85,4302.357054,5,...,2274.070833,0.049620,225.688333,338.5325,0.5,0.028891,0.036439,1.6,1.0,1502.760399
16858,0x78c8,CUS_0xac7b,March,Jessica Wohlt,45,651-72-0851,Developer,27288.85,2524.070833,5,...,2274.070833,0.049620,225.688333,338.5325,0.5,0.028891,0.028268,1.6,1.0,1484.169263
16859,0x78c9,CUS_0xac7b,April,Jessica Wohlt,45,651-72-0851,Developer,27288.85,4302.357054,5,...,2274.070833,0.049620,225.688333,338.5325,0.5,22.380842,0.148886,1.0,1.0,52610.856896
16860,0x78ca,CUS_0xac7b,May,Jessica Wohlt,45,651-72-0851,Developer,27288.85,2524.070833,5,...,2274.070833,0.049620,225.688333,338.5325,0.5,0.028891,0.148816,1.6,1.0,1758.424637

In [ ]:
X = df.drop('Credit_Score',axis=1)
y = df['Credit_Score']

In [ ]:
X

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Monthly_Income_Calc,Debt_to_Income_Ratio,Debt_per_Bank_Account,Debt_per_Credit_Card,Credit_to_Bank_Ratio,EMI_to_Income_Ratio,Investment_to_Income_Ratio,Delayed_Payment_Ratio,Inquiry_per_Credit_Card,Total_Financial_Burden
0,0x1602,CUS_0xd40,January,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,1592.843333,0.042374,202.495000,161.9960,1.0,0.031104,0.050454,1.4,0.8,939.970245
1,0x1603,CUS_0xd40,February,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,4302.357054,3,...,1592.843333,0.042374,202.495000,161.9960,1.0,0.031104,0.074211,3.4,0.8,977.835171
2,0x1604,CUS_0xd40,March,Aaron Maashoh,-500,821-00-0265,Scientist,19114.12,4302.357054,3,...,1592.843333,0.042374,202.495000,161.9960,1.0,0.031104,0.051259,1.4,0.8,941.254470
3,0x1605,CUS_0xd40,April,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,4302.357054,3,...,1592.843333,0.042374,202.495000,161.9960,1.0,0.031104,0.125143,0.8,0.8,1059.013024
4,0x1606,CUS_0xd40,May,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,1592.843333,0.042374,202.495000,161.9960,1.0,0.031104,0.025988,3.4,0.8,900.975102
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16856,0x78c6,CUS_0xac7b,January,Jessica Wohlt,45,651-72-0851,_______,27288.85,2524.070833,5,...,2274.070833,0.049620,225.688333,338.5325,0.5,0.028891,0.045497,1.6,1.0,1523.366536
16857,0x78c7,CUS_0xac7b,February,Jessica Wohlt,45,651-72-0851,Developer,27288.85,4302.357054,5,...,2274.070833,0.049620,225.688333,338.5325,0.5,0.028891,0.036439,1.6,1.0,1502.760399
16858,0x78c8,CUS_0xac7b,March,Jessica Wohlt,45,651-72-0851,Developer,27288.85,2524.070833,5,...,2274.070833,0.049620,225.688333,338.5325,0.5,0.028891,0.028268,1.6,1.0,1484.169263
16859,0x78c9,CUS_0xac7b,April,Jessica Wohlt,45,651-72-0851,Developer,27288.85,4302.357054,5,...,2274.070833,0.049620,225.688333,338.5325,0.5,22.380842,0.148886,1.0,1.0,52610.856896
16860,0x78ca,CUS_0xac7b,May,Jessica Wohlt,45,651-72-0851,Developer,27288.85,2524.070833,5,...,2274.070833,0.049620,225.688333,338.5325,0.5,0.028891,0.148816,1.6,1.0,1758.424637

In [ ]:
y

0            Good
1            Good
2            Good
3            Good
4            Good
           ...
16856    Standard
16857    Standard
16858    Standard
16859    Standard
16860    Standard
Name: Credit_Score, Length: 16861, dtype: object

#Convert target into numbers 0 -->good , 1 -->standard , 2 -->poor

In [ ]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

print("Classes:", label_encoder.classes_)

Classes: ['Good' 'Poor' 'Standard']

In [ ]:
y

array([0, 0, 0, ..., 2, 2, 2])

#Handle categorical columns

In [ ]:
categorical_cols = X.select_dtypes(include=['object']).columns.tolist()
numeric_cols = X.select_dtypes(exclude=['object']).columns.tolist()

print("Categorical columns:", categorical_cols)
print("Numeric columns:", len(numeric_cols))

Categorical columns: ['ID', 'Customer_ID', 'Month', 'Name', 'Age', 'SSN', 'Occupation', 'Type_of_Loan', 'Changed_Credit_Limit', 'Credit_Mix', 'Credit_History_Age', 'Payment_of_Min_Amount', 'Payment_Behaviour', 'Monthly_Balance']
Numeric columns: 23

# doing train test split

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (13488, 37)
Testing data: (3373, 37)

In [ ]:
#

# model 1 --> CatBoost

In [ ]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp313-cp313-manylinux2014_x86_64.whl.metadata (1.4 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.13/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.13/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.13/dist-packages (from catboost) (2.1.3)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.13/dist-packages (from catboost) (2.2.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.13/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.13/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (1.5.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.13/dist-packages (from plotly->catboost) (9.1.4)
Downloading catboost-1.2.10-cp313-cp313-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 9.0 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.10

In [ ]:
from catboost import CatBoostClassifier

cat_features = [
    X_train.columns.get_loc(col)
    for col in categorical_cols
]

catboost_model = CatBoostClassifier(
    iterations=500,
    depth=7,
    learning_rate=0.05,
    loss_function='MultiClass',
    verbose=100,
    random_seed=42
)

catboost_model.fit(
    X_train,
    y_train,
    cat_features=cat_features
)

0:	learn: 1.0503760	total: 995ms	remaining: 8m 16s
100:	learn: 0.4971149	total: 26.5s	remaining: 1m 44s
200:	learn: 0.4656914	total: 52.7s	remaining: 1m 18s
300:	learn: 0.4417287	total: 1m 19s	remaining: 52.3s
400:	learn: 0.4211805	total: 1m 44s	remaining: 25.9s
499:	learn: 0.4037413	total: 2m 10s	remaining: 0us

CatBoostClassifier(depth=7, iterations=500, learning_rate=0.05, loss_function='MultiClass', random_seed=42, verbose=100)

In [ ]:
y_pred_cat = catboost_model.predict(X_test)
y_pred_cat = y_pred_cat.astype(int).ravel()

y_prob_cat = catboost_model.predict_proba(X_test)

In [ ]:
# model 2 --> logistic regression

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

numeric_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

categorical_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer([
    ('num', numeric_pipeline, numeric_cols),
    ('cat', categorical_pipeline, categorical_cols)
])

In [ ]:
X_train_lr = preprocessor.fit_transform(X_train)
X_test_lr = preprocessor.transform(X_test)

print("Training shape:", X_train_lr.shape)
print("Testing shape:", X_test_lr.shape)

Training shape: (13488, 37543)
Testing shape: (3373, 37543)

In [ ]:
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

lr_model.fit(X_train_lr, y_train)

LogisticRegression(max_iter=1000, random_state=42)

In [ ]:
y_pred_lr = lr_model.predict(X_test_lr)
y_prob_lr = lr_model.predict_proba(X_test_lr)

# model evaluation accuracy, precision,Recall and f1

In [ ]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

def evaluate_model(name, y_test, y_pred):
    print("\n", "="*40)
    print(name)
    print("="*40)

    print("Accuracy :", accuracy_score(y_test, y_pred))
    print("Precision:", precision_score(
        y_test, y_pred, average='weighted'
    ))
    print("Recall   :", recall_score(
        y_test, y_pred, average='weighted'
    ))
    print("F1 Score :", f1_score(
        y_test, y_pred, average='weighted'
    ))

evaluate_model(
    "CatBoost",
    y_test,
    y_pred_cat
)

evaluate_model(
    "Logistic Regression",
    y_test,
    y_pred_lr
)

 ========================================
CatBoost
========================================
Accuracy : 0.8357545211977468
Precision: 0.8450977148487636
Recall   : 0.8357545211977468
F1 Score : 0.8353124413188165

 ========================================
Logistic Regression
========================================
Accuracy : 0.7880225318707382
Precision: 0.7879747278833501
Recall   : 0.7880225318707382
F1 Score : 0.787668080027216

In [ ]:
from sklearn.metrics import classification_report

print("CATBOOST CLASSIFICATION REPORT")
print(
    classification_report(
        y_test,
        y_pred_cat,
        target_names=label_encoder.classes_
    )
)

print("\nLOGISTIC REGRESSION CLASSIFICATION REPORT")
print(
    classification_report(
        y_test,
        y_pred_lr,
        target_names=label_encoder.classes_
    )
)

CATBOOST CLASSIFICATION REPORT
              precision    recall  f1-score   support

        Good       0.79      0.90      0.84       595
        Poor       0.78      0.91      0.84      1019
    Standard       0.90      0.77      0.83      1759

    accuracy                           0.84      3373
   macro avg       0.82      0.86      0.84      3373
weighted avg       0.85      0.84      0.84      3373


LOGISTIC REGRESSION CLASSIFICATION REPORT
              precision    recall  f1-score   support

        Good       0.79      0.72      0.75       595
        Poor       0.79      0.79      0.79      1019
    Standard       0.79      0.81      0.80      1759

    accuracy                           0.79      3373
   macro avg       0.79      0.77      0.78      3373
weighted avg       0.79      0.79      0.79      3373

In [ ]:
from sklearn.metrics import classification_report

print("CATBOOST CLASSIFICATION REPORT")
print(
    classification_report(
        y_test,
        y_pred_cat,
        target_names=label_encoder.classes_
    )
)

print("\nLOGISTIC REGRESSION CLASSIFICATION REPORT")
print(
    classification_report(
        y_test,
        y_pred_lr,
        target_names=label_encoder.classes_
    )
)

CATBOOST CLASSIFICATION REPORT
              precision    recall  f1-score   support

        Good       0.79      0.90      0.84       595
        Poor       0.78      0.91      0.84      1019
    Standard       0.90      0.77      0.83      1759

    accuracy                           0.84      3373
   macro avg       0.82      0.86      0.84      3373
weighted avg       0.85      0.84      0.84      3373


LOGISTIC REGRESSION CLASSIFICATION REPORT
              precision    recall  f1-score   support

        Good       0.79      0.72      0.75       595
        Poor       0.79      0.79      0.79      1019
    Standard       0.79      0.81      0.80      1759

    accuracy                           0.79      3373
   macro avg       0.79      0.77      0.78      3373
weighted avg       0.79      0.79      0.79      3373

In [ ]:
from sklearn.metrics import roc_auc_score

auc_cat = roc_auc_score(
    y_test,
    y_prob_cat,
    multi_class='ovr',
    average='weighted'
)

auc_lr = roc_auc_score(
    y_test,
    y_prob_lr,
    multi_class='ovr',
    average='weighted'
)

print("CatBoost ROC-AUC:", auc_cat)
print("Logistic Regression ROC-AUC:", auc_lr)

CatBoost ROC-AUC: 0.9203570818692625
Logistic Regression ROC-AUC: 0.9027598756185236

In [ ]:
results = pd.DataFrame({
    'Model': ['CatBoost', 'Logistic Regression'],

    'Accuracy': [
        accuracy_score(y_test, y_pred_cat),
        accuracy_score(y_test, y_pred_lr)
    ],

    'Precision': [
        precision_score(y_test, y_pred_cat, average='weighted'),
        precision_score(y_test, y_pred_lr, average='weighted')
    ],

    'Recall': [
        recall_score(y_test, y_pred_cat, average='weighted'),
        recall_score(y_test, y_pred_lr, average='weighted')
    ],

    'F1 Score': [
        f1_score(y_test, y_pred_cat, average='weighted'),
        f1_score(y_test, y_pred_lr, average='weighted')
    ],

    'ROC-AUC': [
        auc_cat,
        auc_lr
    ]
})

results

                 Model  Accuracy  Precision    Recall  F1 Score   ROC-AUC
0             CatBoost  0.835755   0.845098  0.835755  0.835312  0.920357
1  Logistic Regression  0.788023   0.787975  0.788023  0.787668  0.902760